CREATE DATABASE winestore;

USE winestore;

-- DROP TABLES
DROP TABLE IF EXISTS UserImage;
DROP TABLE IF EXISTS [User];
DROP TABLE IF EXISTS [Address];
DROP TABLE IF EXISTS Contact;
DROP TABLE IF EXISTS [RolePermission];
DROP TABLE IF EXISTS [Permission];
DROP TABLE IF EXISTS Account;
DROP TABLE IF EXISTS [Role];

-- CREATE "Address" TABLE
CREATE TABLE [Address] (
	AddressId BIGINT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	Line1 VARCHAR(100) NOT NULL,
	Line2 VARCHAR(100),
	Line3 VARCHAR(100),
	City VARCHAR(50) NOT NULL,
	State VARCHAR(50) NOT NULL,
	Country VARCHAR(50) NOT NULL,
	Postal VARCHAR(12) NOT NULL,
	CreatedBy VARCHAR(50) NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	ModifiedBy VARCHAR(50) NOT NULL,
	ModifiedDate DATETIME2 NOT NULL
)

-- CREATE "Contact" TABLE
CREATE TABLE Contact (
	ContactId BIGINT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	Mobile VARCHAR(10) NOT NULL,
	Tel VARCHAR(10),
	Fax VARCHAR(20),
	CreatedBy VARCHAR(50) NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	ModifiedBy VARCHAR(50) NOT NULL,
	ModifiedDate DATETIME2 NOT NULL
)	

-- CREATE "Role" TABLE
CREATE TABLE Role (
	RoleId BIGINT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	Name VARCHAR(20) NOT NULL,
	CreatedBy VARCHAR(50) NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	ModifiedBy VARCHAR(50) NOT NULL,
	ModifiedDate DATETIME2 NOT NULL
)

-- CREATE "Permission" TABLE
CREATE TABLE Permission (
	PermissionId BIGINT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	Name VARCHAR(20) NOT NULL,
	CreatedBy VARCHAR(50) NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	ModifiedBy VARCHAR(50) NOT NULL,
	ModifiedDate DATETIME2 NOT NULL
)

-- CREATE "RolePermission" TABLE
CREATE TABLE RolePermission (
	RoleId BIGINT FOREIGN KEY REFERENCES [Role] (RoleId),
	PermissionId BIGINT FOREIGN KEY REFERENCES Permission (PermissionId)
)

-- CREATE "Account" TABLE
CREATE TABLE Account (
	AccountId BIGINT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	RoleId BIGINT FOREIGN KEY REFERENCES [Role] (RoleId),
	Email VARCHAR(50) UNIQUE NOT NULL,
	[Password] VARCHAR(128) NOT NULL,
	Verified BIT NOT NULL DEFAULT 0,
	CreatedBy VARCHAR(50) NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	ModifiedBy VARCHAR(50) NOT NULL,
	ModifiedDate DATETIME2 NOT NULL
)

-- CREATE "User" TABLE
CREATE TABLE [User] (
	UserId BIGINT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	AddressId BIGINT FOREIGN KEY REFERENCES [Address] (AddressId),
	ContactId BIGINT FOREIGN KEY REFERENCES Contact (ContactId),
	AccountId BIGINT FOREIGN KEY REFERENCES Account (AccountId),
	Salutation VARCHAR(5) NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	MiddleName VARCHAR(50),
	LastName VARCHAR(50) NOT NULL,
	Suffix VARCHAR(5) NULL,
	BirthDate DATE NOT NULL,
	Active BIT NOT NULL DEFAULT 0,
	CreatedBy VARCHAR(50) NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	ModifiedBy VARCHAR(50) NOT NULL,
	ModifiedDate DATETIME2 NOT NULL
);

-- CREATE "UserImage" TABLE
CREATE TABLE UserImage (
	UserImageId BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	UserId BIGINT FOREIGN KEY REFERENCES [User] (UserId),
	ImagePath VARCHAR(150) NOT NULL,
	CreatedBy VARCHAR(50) NOT NULL,
	CreatedDate DATETIME2 NOT NULL,
	ModifiedBy VARCHAR(50) NOT NULL,
	ModifiedDate DATETIME2 NOT NULL
)
